name: cs415_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  pdf: ^3.10.8
  printing: ^5.11.0
  url_launcher: ^6.1.7
  firebase_core: ^2.24.2
  firebase_database: ^10.3.8
  firebase_auth: ^4.15.3
  connectivity_plus: ^5.0.2
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Add your image assets here
  assets:
    - assets/images/header.png
    - assets/images/usp_logo.svg
    - assets/images/student.png
    - assets/images/homepage.png 